package com.lovehai.helloSecurity;

import org.mybatis.spring.annotation.MapperScan;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;


// Generated by https://start.springboot.io
// 优质的 spring/boot/data/security/cloud 框架中文文档尽在 => https://springdoc.cn
@SpringBootApplication
@ComponentScan(basePackages = {"com.lovehai.helloSecurity.config",
        "com.lovehai.helloSecurity.controller",
        "com.lovehai.helloSecurity.service"
})
@MapperScan("com.lovehai.helloSecurity.mapper")
public class HelloSecurityApplication {

    public static void main(String[] args) {
        SpringApplication.run(HelloSecurityApplication.class, args);
    }

}
