package com.lovehai.helloSecurity.mapper;

import com.lovehai.helloSecurity.entity.UserAuthDetail;
import com.lovehai.helloSecurity.entity.UserAuthDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserAuthDetailMapper {
    long countByExample(UserAuthDetailExample example);

    int deleteByExample(UserAuthDetailExample example);

    int deleteByPrimaryKey(Long id);

    int insert(UserAuthDetail record);

    int insertSelective(UserAuthDetail record);

    List<UserAuthDetail> selectByExample(UserAuthDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<UserAuthDetail> selectByExampleSelective(@Param("example") UserAuthDetailExample example, @Param("selective") UserAuthDetail.Column... selective);

    UserAuthDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserAuthDetail selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") UserAuthDetail.Column... selective);

    int updateByExampleSelective(@Param("record") UserAuthDetail record, @Param("example") UserAuthDetailExample example);

    int updateByExample(@Param("record") UserAuthDetail record, @Param("example") UserAuthDetailExample example);

    int updateByPrimaryKeySelective(UserAuthDetail record);

    int updateByPrimaryKey(UserAuthDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserAuthDetail selectOneByExample(UserAuthDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_auth_detail
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    UserAuthDetail selectOneByExampleSelective(@Param("example") UserAuthDetailExample example, @Param("selective") UserAuthDetail.Column... selective);
}