appName: SpringDubboProvider

zookeeper:
  address: 47.103.49.207
mysql:
  address: 127.0.0.1
spring:
  application:
    name: ${appName}
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${mysql.address}:3306/love_sea_base?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
dubbo:
  application:
    logger: slf4j
    name: ${appName}
    serialize-check-status: STRICT
  consumer:
    check: false
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
  protocol:
    name: dubbo
    port: 20880
server:
  port: 8484
mybatis:
  mapper-locations: classpath:mappers/*xml
  type-aliases-package: com.LoveSea.SpringDubbo.model.entity
  config: classpath:mybatis-config.xml


logging:
  config: classpath:logback-boot.xml