package com.loveSea.springDubbo.mybatis.mapper;


import com.loveSea.springDubbo.model.enitiy.lsHero;
import com.loveSea.springDubbo.mybatis.example.lsHeroExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface lsHeroMapper {
    long countByExample(lsHeroExample example);

    int deleteByExample(lsHeroExample example);

    int deleteByPrimaryKey(Long id);

    int insert(lsHero record);

    int insertSelective(lsHero record);

    List<lsHero> selectByExample(lsHeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_hero
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<lsHero> selectByExampleSelective(@Param("example") lsHeroExample example, @Param("selective") lsHero.Column... selective);

    lsHero selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_hero
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    lsHero selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") lsHero.Column... selective);

    int updateByExampleSelective(@Param("record") lsHero record, @Param("example") lsHeroExample example);

    int updateByExample(@Param("record") lsHero record, @Param("example") lsHeroExample example);

    int updateByPrimaryKeySelective(lsHero record);

    int updateByPrimaryKey(lsHero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_hero
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<lsHero> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_hero
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<lsHero> list, @Param("selective") lsHero.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_hero
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    lsHero selectOneByExample(lsHeroExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_hero
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    lsHero selectOneByExampleSelective(@Param("example") lsHeroExample example, @Param("selective") lsHero.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_hero
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(lsHero record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ls_hero
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(lsHero record);
}