// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: MqInfo.proto
// Protobuf Java Version: 4.28.3

package com.loveSea.nettyShow.protobuf;

public final class MqInfo {
  private MqInfo() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 3,
      /* suffix= */ "",
      MqInfo.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MqInfoMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MqInfoMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string topic = 1;</code>
     * @return Whether the topic field is set.
     */
    boolean hasTopic();
    /**
     * <code>required string topic = 1;</code>
     * @return The topic.
     */
    java.lang.String getTopic();
    /**
     * <code>required string topic = 1;</code>
     * @return The bytes for topic.
     */
    com.google.protobuf.ByteString
        getTopicBytes();

    /**
     * <code>required string tag = 2;</code>
     * @return Whether the tag field is set.
     */
    boolean hasTag();
    /**
     * <code>required string tag = 2;</code>
     * @return The tag.
     */
    java.lang.String getTag();
    /**
     * <code>required string tag = 2;</code>
     * @return The bytes for tag.
     */
    com.google.protobuf.ByteString
        getTagBytes();

    /**
     * <code>required string key = 3;</code>
     * @return Whether the key field is set.
     */
    boolean hasKey();
    /**
     * <code>required string key = 3;</code>
     * @return The key.
     */
    java.lang.String getKey();
    /**
     * <code>required string key = 3;</code>
     * @return The bytes for key.
     */
    com.google.protobuf.ByteString
        getKeyBytes();

    /**
     * <code>required string message = 4;</code>
     * @return Whether the message field is set.
     */
    boolean hasMessage();
    /**
     * <code>required string message = 4;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>required string message = 4;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>required string producerGroup = 5;</code>
     * @return Whether the producerGroup field is set.
     */
    boolean hasProducerGroup();
    /**
     * <code>required string producerGroup = 5;</code>
     * @return The producerGroup.
     */
    java.lang.String getProducerGroup();
    /**
     * <code>required string producerGroup = 5;</code>
     * @return The bytes for producerGroup.
     */
    com.google.protobuf.ByteString
        getProducerGroupBytes();

    /**
     * <code>required string consumerGroup = 6;</code>
     * @return Whether the consumerGroup field is set.
     */
    boolean hasConsumerGroup();
    /**
     * <code>required string consumerGroup = 6;</code>
     * @return The consumerGroup.
     */
    java.lang.String getConsumerGroup();
    /**
     * <code>required string consumerGroup = 6;</code>
     * @return The bytes for consumerGroup.
     */
    com.google.protobuf.ByteString
        getConsumerGroupBytes();
  }
  /**
   * Protobuf type {@code MqInfoMessage}
   */
  public static final class MqInfoMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:MqInfoMessage)
      MqInfoMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 3,
        /* suffix= */ "",
        MqInfoMessage.class.getName());
    }
    // Use MqInfoMessage.newBuilder() to construct.
    private MqInfoMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private MqInfoMessage() {
      topic_ = "";
      tag_ = "";
      key_ = "";
      message_ = "";
      producerGroup_ = "";
      consumerGroup_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.loveSea.nettyShow.protobuf.MqInfo.internal_static_MqInfoMessage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.loveSea.nettyShow.protobuf.MqInfo.internal_static_MqInfoMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage.class, com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage.Builder.class);
    }

    private int bitField0_;
    public static final int TOPIC_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object topic_ = "";
    /**
     * <code>required string topic = 1;</code>
     * @return Whether the topic field is set.
     */
    @java.lang.Override
    public boolean hasTopic() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string topic = 1;</code>
     * @return The topic.
     */
    @java.lang.Override
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          topic_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string topic = 1;</code>
     * @return The bytes for topic.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TAG_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object tag_ = "";
    /**
     * <code>required string tag = 2;</code>
     * @return Whether the tag field is set.
     */
    @java.lang.Override
    public boolean hasTag() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string tag = 2;</code>
     * @return The tag.
     */
    @java.lang.Override
    public java.lang.String getTag() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          tag_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string tag = 2;</code>
     * @return The bytes for tag.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTagBytes() {
      java.lang.Object ref = tag_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        tag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int KEY_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object key_ = "";
    /**
     * <code>required string key = 3;</code>
     * @return Whether the key field is set.
     */
    @java.lang.Override
    public boolean hasKey() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string key = 3;</code>
     * @return The key.
     */
    @java.lang.Override
    public java.lang.String getKey() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          key_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string key = 3;</code>
     * @return The bytes for key.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getKeyBytes() {
      java.lang.Object ref = key_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        key_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MESSAGE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object message_ = "";
    /**
     * <code>required string message = 4;</code>
     * @return Whether the message field is set.
     */
    @java.lang.Override
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string message = 4;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          message_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string message = 4;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRODUCERGROUP_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object producerGroup_ = "";
    /**
     * <code>required string producerGroup = 5;</code>
     * @return Whether the producerGroup field is set.
     */
    @java.lang.Override
    public boolean hasProducerGroup() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required string producerGroup = 5;</code>
     * @return The producerGroup.
     */
    @java.lang.Override
    public java.lang.String getProducerGroup() {
      java.lang.Object ref = producerGroup_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          producerGroup_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string producerGroup = 5;</code>
     * @return The bytes for producerGroup.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getProducerGroupBytes() {
      java.lang.Object ref = producerGroup_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        producerGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONSUMERGROUP_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object consumerGroup_ = "";
    /**
     * <code>required string consumerGroup = 6;</code>
     * @return Whether the consumerGroup field is set.
     */
    @java.lang.Override
    public boolean hasConsumerGroup() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required string consumerGroup = 6;</code>
     * @return The consumerGroup.
     */
    @java.lang.Override
    public java.lang.String getConsumerGroup() {
      java.lang.Object ref = consumerGroup_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          consumerGroup_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string consumerGroup = 6;</code>
     * @return The bytes for consumerGroup.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getConsumerGroupBytes() {
      java.lang.Object ref = consumerGroup_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        consumerGroup_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTopic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTag()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasKey()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMessage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasProducerGroup()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasConsumerGroup()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, topic_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, tag_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, key_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, message_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, producerGroup_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, consumerGroup_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, topic_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, tag_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, key_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, message_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(5, producerGroup_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(6, consumerGroup_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage)) {
        return super.equals(obj);
      }
      com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage other = (com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage) obj;

      if (hasTopic() != other.hasTopic()) return false;
      if (hasTopic()) {
        if (!getTopic()
            .equals(other.getTopic())) return false;
      }
      if (hasTag() != other.hasTag()) return false;
      if (hasTag()) {
        if (!getTag()
            .equals(other.getTag())) return false;
      }
      if (hasKey() != other.hasKey()) return false;
      if (hasKey()) {
        if (!getKey()
            .equals(other.getKey())) return false;
      }
      if (hasMessage() != other.hasMessage()) return false;
      if (hasMessage()) {
        if (!getMessage()
            .equals(other.getMessage())) return false;
      }
      if (hasProducerGroup() != other.hasProducerGroup()) return false;
      if (hasProducerGroup()) {
        if (!getProducerGroup()
            .equals(other.getProducerGroup())) return false;
      }
      if (hasConsumerGroup() != other.hasConsumerGroup()) return false;
      if (hasConsumerGroup()) {
        if (!getConsumerGroup()
            .equals(other.getConsumerGroup())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTopic()) {
        hash = (37 * hash) + TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getTopic().hashCode();
      }
      if (hasTag()) {
        hash = (37 * hash) + TAG_FIELD_NUMBER;
        hash = (53 * hash) + getTag().hashCode();
      }
      if (hasKey()) {
        hash = (37 * hash) + KEY_FIELD_NUMBER;
        hash = (53 * hash) + getKey().hashCode();
      }
      if (hasMessage()) {
        hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
        hash = (53 * hash) + getMessage().hashCode();
      }
      if (hasProducerGroup()) {
        hash = (37 * hash) + PRODUCERGROUP_FIELD_NUMBER;
        hash = (53 * hash) + getProducerGroup().hashCode();
      }
      if (hasConsumerGroup()) {
        hash = (37 * hash) + CONSUMERGROUP_FIELD_NUMBER;
        hash = (53 * hash) + getConsumerGroup().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MqInfoMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MqInfoMessage)
        com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.loveSea.nettyShow.protobuf.MqInfo.internal_static_MqInfoMessage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.loveSea.nettyShow.protobuf.MqInfo.internal_static_MqInfoMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage.class, com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage.Builder.class);
      }

      // Construct using com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        topic_ = "";
        tag_ = "";
        key_ = "";
        message_ = "";
        producerGroup_ = "";
        consumerGroup_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.loveSea.nettyShow.protobuf.MqInfo.internal_static_MqInfoMessage_descriptor;
      }

      @java.lang.Override
      public com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage getDefaultInstanceForType() {
        return com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage.getDefaultInstance();
      }

      @java.lang.Override
      public com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage build() {
        com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage buildPartial() {
        com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage result = new com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.topic_ = topic_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.tag_ = tag_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.key_ = key_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.message_ = message_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.producerGroup_ = producerGroup_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.consumerGroup_ = consumerGroup_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage) {
          return mergeFrom((com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage other) {
        if (other == com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage.getDefaultInstance()) return this;
        if (other.hasTopic()) {
          topic_ = other.topic_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.hasTag()) {
          tag_ = other.tag_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.hasKey()) {
          key_ = other.key_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (other.hasMessage()) {
          message_ = other.message_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.hasProducerGroup()) {
          producerGroup_ = other.producerGroup_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (other.hasConsumerGroup()) {
          consumerGroup_ = other.consumerGroup_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTopic()) {
          return false;
        }
        if (!hasTag()) {
          return false;
        }
        if (!hasKey()) {
          return false;
        }
        if (!hasMessage()) {
          return false;
        }
        if (!hasProducerGroup()) {
          return false;
        }
        if (!hasConsumerGroup()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                topic_ = input.readBytes();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                tag_ = input.readBytes();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                key_ = input.readBytes();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                message_ = input.readBytes();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                producerGroup_ = input.readBytes();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                consumerGroup_ = input.readBytes();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object topic_ = "";
      /**
       * <code>required string topic = 1;</code>
       * @return Whether the topic field is set.
       */
      public boolean hasTopic() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string topic = 1;</code>
       * @return The topic.
       */
      public java.lang.String getTopic() {
        java.lang.Object ref = topic_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            topic_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       * @return The bytes for topic.
       */
      public com.google.protobuf.ByteString
          getTopicBytes() {
        java.lang.Object ref = topic_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          topic_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string topic = 1;</code>
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        topic_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        topic_ = getDefaultInstance().getTopic();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>required string topic = 1;</code>
       * @param value The bytes for topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopicBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        topic_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object tag_ = "";
      /**
       * <code>required string tag = 2;</code>
       * @return Whether the tag field is set.
       */
      public boolean hasTag() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string tag = 2;</code>
       * @return The tag.
       */
      public java.lang.String getTag() {
        java.lang.Object ref = tag_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            tag_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string tag = 2;</code>
       * @return The bytes for tag.
       */
      public com.google.protobuf.ByteString
          getTagBytes() {
        java.lang.Object ref = tag_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          tag_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string tag = 2;</code>
       * @param value The tag to set.
       * @return This builder for chaining.
       */
      public Builder setTag(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        tag_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>required string tag = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTag() {
        tag_ = getDefaultInstance().getTag();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>required string tag = 2;</code>
       * @param value The bytes for tag to set.
       * @return This builder for chaining.
       */
      public Builder setTagBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        tag_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object key_ = "";
      /**
       * <code>required string key = 3;</code>
       * @return Whether the key field is set.
       */
      public boolean hasKey() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string key = 3;</code>
       * @return The key.
       */
      public java.lang.String getKey() {
        java.lang.Object ref = key_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            key_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string key = 3;</code>
       * @return The bytes for key.
       */
      public com.google.protobuf.ByteString
          getKeyBytes() {
        java.lang.Object ref = key_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          key_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string key = 3;</code>
       * @param value The key to set.
       * @return This builder for chaining.
       */
      public Builder setKey(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearKey() {
        key_ = getDefaultInstance().getKey();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>required string key = 3;</code>
       * @param value The bytes for key to set.
       * @return This builder for chaining.
       */
      public Builder setKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        key_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>required string message = 4;</code>
       * @return Whether the message field is set.
       */
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string message = 4;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            message_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string message = 4;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string message = 4;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        message_ = getDefaultInstance().getMessage();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>required string message = 4;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        message_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object producerGroup_ = "";
      /**
       * <code>required string producerGroup = 5;</code>
       * @return Whether the producerGroup field is set.
       */
      public boolean hasProducerGroup() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required string producerGroup = 5;</code>
       * @return The producerGroup.
       */
      public java.lang.String getProducerGroup() {
        java.lang.Object ref = producerGroup_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            producerGroup_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string producerGroup = 5;</code>
       * @return The bytes for producerGroup.
       */
      public com.google.protobuf.ByteString
          getProducerGroupBytes() {
        java.lang.Object ref = producerGroup_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          producerGroup_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string producerGroup = 5;</code>
       * @param value The producerGroup to set.
       * @return This builder for chaining.
       */
      public Builder setProducerGroup(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        producerGroup_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>required string producerGroup = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearProducerGroup() {
        producerGroup_ = getDefaultInstance().getProducerGroup();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>required string producerGroup = 5;</code>
       * @param value The bytes for producerGroup to set.
       * @return This builder for chaining.
       */
      public Builder setProducerGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        producerGroup_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object consumerGroup_ = "";
      /**
       * <code>required string consumerGroup = 6;</code>
       * @return Whether the consumerGroup field is set.
       */
      public boolean hasConsumerGroup() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required string consumerGroup = 6;</code>
       * @return The consumerGroup.
       */
      public java.lang.String getConsumerGroup() {
        java.lang.Object ref = consumerGroup_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            consumerGroup_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string consumerGroup = 6;</code>
       * @return The bytes for consumerGroup.
       */
      public com.google.protobuf.ByteString
          getConsumerGroupBytes() {
        java.lang.Object ref = consumerGroup_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          consumerGroup_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string consumerGroup = 6;</code>
       * @param value The consumerGroup to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerGroup(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        consumerGroup_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>required string consumerGroup = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearConsumerGroup() {
        consumerGroup_ = getDefaultInstance().getConsumerGroup();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>required string consumerGroup = 6;</code>
       * @param value The bytes for consumerGroup to set.
       * @return This builder for chaining.
       */
      public Builder setConsumerGroupBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        consumerGroup_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:MqInfoMessage)
    }

    // @@protoc_insertion_point(class_scope:MqInfoMessage)
    private static final com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage();
    }

    public static com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MqInfoMessage>
        PARSER = new com.google.protobuf.AbstractParser<MqInfoMessage>() {
      @java.lang.Override
      public MqInfoMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<MqInfoMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MqInfoMessage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.loveSea.nettyShow.protobuf.MqInfo.MqInfoMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MqInfoMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MqInfoMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014MqInfo.proto\"w\n\rMqInfoMessage\022\r\n\005topic" +
      "\030\001 \002(\t\022\013\n\003tag\030\002 \002(\t\022\013\n\003key\030\003 \002(\t\022\017\n\007mess" +
      "age\030\004 \002(\t\022\025\n\rproducerGroup\030\005 \002(\t\022\025\n\rcons" +
      "umerGroup\030\006 \002(\tB(\n\036com.loveSea.nettyShow" +
      ".protobufB\006MqInfo"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_MqInfoMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MqInfoMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_MqInfoMessage_descriptor,
        new java.lang.String[] { "Topic", "Tag", "Key", "Message", "ProducerGroup", "ConsumerGroup", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
